### ISSUE TITLE
Clean up getting started

### ISSUE THREAD

**Issue by balloob** [home-assistant/home-assistant.github.io#1603]
Our getting started section has grown over time and the current structure is no longer a getting started guide but more a look at all the stuff you can do.

I think that we have to take a step back and see what is really important. Anything that is not the most important is distracting and should be moved away from the main menu/getting started. It looks too daunting now for new users.

So what is most important? Our Raspberry Pi image. We have 70% of our users using a Pi and that is awesome. I think the last time I checked 80% of them are on a Pi 3 so having it evolve around that will be even better.

So here are some improvements that I can see will improve our guide:
 - Limit getting started to the essentials:
   - Just the RPi image on a Pi 3
   - config 101 (but no advanced stuff like customize)
   - adding your first integrations
   - adding first automation. 
 - Create a Docs section and include it in top nav. This is where most of the getting started will move to.
 - Create special UI for docs. Currently our UI is not good for having long nav bars. Something like [this](https://www.polymer-project.org/1.0/start/) and [this](http://redux.js.org/) is beautiful. You can individually scroll the nav from the main content. I can see us having to implement a special layout that doesn't contain the normal header/sidebar just for docs sections.
 - Ecosystem is a great section, but let's move it to the documentation. We should also go through the getting started and find things that we should move to the ecosystem section. Like [autostart](https://home-assistant.io/getting-started/autostart/) and [Add to Android home screen](https://home-assistant.io/getting-started/android/), 
 - "Details" group and "advanced topics" group can stop existing on their own and also move to the docs header.

What do people think of this idea?

----

Extraction of items/tasks:

- [x] Rework "Getting started". Keep it focused on RPi and as simple as possible #2055
- [x] Create "Docs" section #2055
- [ ] Create improved layout for documentation #3477
- [x] Move Ecosystem to documentation #2055
- [x] Merge "Details" and "advanced topics" into docs #2055
- [x] Split MQTT documentation #2019 #2055
- [x] Create a Tools section. `hass`, scripts, Developer tools, etc #2114
- [x] Improve the FAQ sections of the different topics
- [x] Sync Component details and Docs (eg. Automation)

**Comment by keatontaylor** [comment]
I approve, but I would encourage placing any advanced topic within the docs of the underlying component. This would seriously simplify navigation and I think help other see the big picture.

**Comment by balloob** [comment]
I agree with that, I think that breaking component docs into subsections would help tremendously. We already do this for Z-Wave but I feel like MQTT could use that too

**Comment by lwis** [comment]
I'd also like to add that platform docs aren't obvious. 

My thoughts; advertise all the platforms as we kind of do on the components page already, but upon selecting a platform some information/description is displayed before the list of individual components - with a link to further platform documentation.

**Comment by mehuman** [comment]
Initial thoughts.
- The biggest barrier is how daunting the config can feel. The Getting Started section should get the person to a clicky usable thing in as short as possible. Discovery in components is huge for this. Focusing on RPI3 should also be prioritized. If 80% of 70% of users go that route it's a large portion of the userbase. A step by step with a copy and paste generic config could get someone new going in 5 minutes.
- Config 101 is important. Personally I like having my files split up and referenced by the main config. I didn't even know this was an option until I ran across it under examples.
- I love the idea of platforms and then components listed underneath. When I'm looking to do something I frequently have to check both the platform and then the component.
- An automated way to show which options are available for which component would be great. It's already defined in the component but I've had to poke around in the code to see that the Flux Led doesn't support color_loop for example.
- Automation is another barrier. Examples showing how to reference components using Jinja2 would be very helpful.
- A Tools section. Show the purpose of the developer tools and how to use them.

Another thought I had was an ask HA blog. Have users ask questions about how to do something and write it up as a blog post. These could be archived as examples of what you can do and how to do it. I'd be happy to help with it. Weekly might be too frequent but monthly should be doable.

**Comment by bassclarinetl2** [comment]
I'd be happy to contribute some of my configs to a config 101 if so desired.  Something we find (or I at least) in the "support" chat (to the point that it's become a awful joke) is how to post formatted code snippets (e.g. between 3 backticks).  Perhaps it might be worth having a template of sorts (what to include in a help request. not mandatory but recommended) or a primer on some of the eccentricities of markdown.

With regards to ui, would having expanding blocks (I think they're called accordions) separating the basic, intermediate, and the what the hell have I just done in the same page but have the upper levels compacted by default.

Would it be worth having a FAQ section based on the questions that pop up often either in chat or the forums.

Ok, that's enough rambling.  Time for bed.

**Comment by lwis** [comment]
@bassclarinetl2 currently the configs in the docs are only maintainers, but I can't personally see any problem with adding a community section with links to various GitHubs and a short desc.

**Comment by Maxr1998** [comment]
@balloob great ideas, that would make a lot of sense.
Especially when you look at the Automation section of the Getting started guide, you are pretty overwhelmed. Then again, the Components → Automation falls rather short. I think it should be swapped, a getting started with a few meaningful examples, easily understandable, and the full documentation with good explanations of the configuration variables in the components section with a lot of advanced use cases.

**Comment by fabaff** [comment]
Extraction of items/tasks:

- [ ] Rework "Getting started". Keep it focused on RPi and as simple as possible
- [ ] Create "Docs" section
- [ ] Create improved layout for documentation 
- [ ] Move Ecosystem to documentation 
- [ ] Merge "Details" and "advanced topics" into docs
- [ ] Split MQTT documentation #2019 
- [ ] Create a Tools section. `hass`, scripts, Developer tools, etc
- [ ] Improve the FAQ sections of the different topics
- [ ] Sync Component details and Docs (eg. Automation)

**Comment by robbiet480** [comment]
Is this still a valid issue @balloob?

**Comment by pcopa** [comment]
Systems: win10 and rpi3

I'm new to this, so please have mercy
When following the instructions "Installing Hass.io" for a first install, I got to the part "You will be able to reach your installation at http://hassio.local:8123." and everything seems to be working.  Even the HomeAssistance information page is accumulating errors. (Only I did have to replace "http://hassio.local" with "my IP address").

Now I need to make changes to the configuration files, but whatever I try the Pi3 is refusing my attemps.
What is the default username and password to log into this virgin install? And should I have added a SSH file in the root to enable SSH?

Thanks for your help

**Comment by Maxr1998** [comment]
This is the issue tracker for the home-assistant server itself, and no support channel.
Kindly take a look at one of these: https://home-assistant.io/help/ :)

I suggest asking in the Discord chat, there's an extra channel for hass.io ;)

**Comment by pcopa** [comment]
Thanks for the direction

**Comment by fabaff** [comment]
Last remaining issue splitted out as #3477.
